# This file is generated by ModuleSync, do not edit.
require 'puppetlabs_spec_helper/module_spec_helper'

# put local configuration and setup into spec_helper_local
if File.exist?(File.expand_path('spec_helper_local.rb', File.dirname(__FILE__)))
  require_relative 'spec_helper_local'
end
